#!/bin/sh
if [ -z "$1" ]
  then
    echo "Usage: $0 <pg-uri>"
    exit 1
fi
QUERY="select trunc(extract('epoch' from now() - xact_start)) as \"txn age\", substring(query for 60) || '...' as \"query\" from pg_catalog.pg_stat_activity where state = 'idle in transaction' and application_name not like 'pgAdmin%'"
psql -c "$QUERY" $1
