#!/bin/sh
if [ -z "$1" ]
  then
    echo "Usage: $0 <pg-uri>"
    exit 1
fi
QUERY="select queryid, calls, trunc(calls * 100.0 / sum(calls) over()) as \"% calls\", trunc(total_exec_time * 100.0 / sum(total_exec_time) over()) as \"% time\", trunc(mean_exec_time) as \"avg time\", substring(query for 40) || '...' as \"query\" from public.pg_stat_statements order by calls desc limit 10"
psql -c "$QUERY" $1
