#!/bin/sh
if [ -z "$1" ]
  then
    echo "Usage: $0 <pg-uri>"
    exit 1
fi
QUERY="select queryid, trunc(total_exec_time * 100.0 / sum(total_exec_time) over()) as \"% time\", trunc(mean_exec_time) as \"avg time\", calls, substring(query for 40) || '...' as \"query\" from public.pg_stat_statements order by total_exec_time desc limit 10"
psql -c "$QUERY" $1
